# Generated by Django 2.2.5 on 2020-05-15 08:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('gid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
            options={
                'db_table': 'buildings',
            },
        ),
        migrations.CreateModel(
            name='CampingArea',
            fields=[
                ('gid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
            options={
                'db_table': 'camping_areas',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('gid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
            options={
                'db_table': 'places',
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('gid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
            options={
                'db_table': 'pools',
            },
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('gid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
            options={
                'db_table': 'trees',
            },
        ),
    ]
