# Generated by Django 2.2.5 on 2020-06-06 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CampMAP', '0003_auto_20200605_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='camper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='camper_id', to='CampMAP.Camper'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='place_id', to='CampMAP.Place'),
        ),
        migrations.AlterModelTable(
            name='camper',
            table=None,
        ),
    ]
